apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "demo-backend.labels" . | nindent 4 }}
data:
  MONGO_DB: {{ .Values.config.MONGO_DB_NAME }}
  NODE_ENV: {{ .Values.config.NODE_ENV }}
  