apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_URL: {{ .Values.secret.MONGO_URL | b64enc | quote }}
  REDIS_URL: {{ .Values.secret.REDIS_URL | b64enc | quote }}
